version: 2.1
orbs:
  node: circleci/node@4.7
workflows:
  udacity-todos:
    jobs:
      version: "16.10"
      pkg-manager: npm
    build:
    docker:
      - image: "cimg/node:16.10"
    steps:
      - node/install:
          node-version: "16.10"
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run client:install
      - run:
          name: Install API Dependencies
          command: |
            npm run server:install
      - run:
          name: Front-End Build
          command: |
            npm run client:build
      - run:
          name: API Build
          command: |
            npm run server:build
    deploy:
      docker:
        - image: "cimg/base:stable"
      steps:
        - node/install:
            node-version: "16.10"
        - eb/setup
        - aws-cli/setup
        - checkout
        - run:
            name: Deploy App
            command: |
              npm run deploy
